name: Workflow Manual de Manuel Yerbes

on:
  workflow_dispatch:
    inputs:
      nombre_apellidos:
        description: 'Por favor, introduce tu nombre y apellidos'
        required: true
        default: ''

jobs:
  imprimir-nombre:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir nombre completo por consola
        run: echo "Mi nombre completo es ${{ github.event.inputs.nombre_apellidos }}"